print("╔══════════════════════════════════════════════╗")
print("║       STUDENT BIO CARD                       ║")
print("╔══════════════════════════════════════════════╗")
print("║ Name    : Jeevitha Divakar                   ║")
print("║ Age     : 22                                 ║")
print("║ Course  : Python Programming                 ║")
print("║ College : East West Institute of Technology  ║")
print("║ Email   : jeevithadivakar2020@gmail.com      ║")
print("╚══════════════════════════════════════════════╝")